fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    agent: "#{source_dir}/modules/agent"
    packages: "#{source_dir}/modules/packages"
    timezone: "#{source_dir}/modules/timezone"
